spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application:
    name: openmarket
  datasource:
    url: jdbc:mysql://localhost:13306/openmarket
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin@123
  data:
    redis:
      host: 127.0.0.1
      port: 6380
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
jwt:
  refresh-token-expired-day: 30
  access-token-expired-minutes: 5
  algorithm: HS256
external:
  payment:
    url: http://127.0.0.1:8080/test/payment

